apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: default
type: Opaque
stringData:
    BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:hvEMvjogM6EqIPmDrzfAU/07IecklfNUCETOusezlg==,iv:vpwODnxRxFkYh3CbNxDOnrIO/BpdOD2fxuXKSXtdXho=,tag:XAd0D8VxSL8d8L55Iwblug==,type:str]
    GOPLACES_API_KEY: ENC[AES256_GCM,data:CRJxFWdN6i4vEVWZ6QsMeGH5j/yJz5lQP9h+tc9gUCyW4hbdIXGS,iv:kldZLSk1M/XeVv/pyCiSv4sR9mYoEbxrAJU5AXXl8XI=,tag:LC9UbM8u4wVV2Zo+9//BxQ==,type:str]
    MATRIX_PASSWORD: ENC[AES256_GCM,data:geNcVhDUD9rerrur,iv:f2dxnrFlLfzpN2rebJlCKeVFAQ0/ag9b7rgcbdrzA0I=,tag:LhExq5yCihs1Lak9PQsz0w==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:a4l2vPSPUnDTb2qqflXbsK6N+OS4jNQgnB7mw71/88pFRUVLGeDRHgOn31/FUCoLkGGNxJes386OPfYBux0kIg==,iv:mhBIHhkz8QdGtDV8sm9OSWgSSMBxWC9C4+sFkKkdJrY=,tag:Bpuudy90W0BjlYQy+Rp5dA==,type:str]
    OPENCLAW_REMOTE_TOKEN: ENC[AES256_GCM,data:f8Pwzua3pjUVDDHyWfXJY13FmyI13+F5OiCEusJcvT4njOAfzsYb3lcuv3I4PyiQVhx2zl166ClmogaxNPDNYQ==,iv:YiX54IyTmpLkT36D8V9YgU+Qxbq7UpDDTnVuKQwnjxU=,tag:gv39erYxd0e+JwlcYRyfcw==,type:str]
    GOG_KEYRING_PASSWORD: ENC[AES256_GCM,data:wmXOJVo8lQe7IwDZ7g==,iv:fvr60DMGQfqCkDECZgI/WhFbFCULoUdn/7QqMGepyF8=,tag:u6Lof6MrUY3t2dmrU0YrUA==,type:str]
sops:
    age:
        - recipient: age1n7m4qddze6jmky0zzgasxr2fsea25t4ejppzv0flftsuzhrytgaqm49c2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId1hyK1dpWUs3Uy9vMWJ5
            VlNzMUdiTGV6dmRGdCtvMDVndjBTRVA5ZVZvCkc1MHQySG5oNXd0TEx2N1JOZnZV
            emFTa0dmaEZKc0tKNndsZ0E0OGRqa3cKLS0tIHA0ZjVWamFhd3NHcDdDbyt5d21j
            OUZaL1ppWDBLMXRJSWJWNFRqQ0toTXMK1uyoJHm8oTJSuDZKQvjpUu1TRKuc6VVS
            PRON5bOgVpJ6D9HY6gZFEsp355z7cEYlNCdNvl/ksOPKIqXDaEOb+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T08:38:14Z"
    mac: ENC[AES256_GCM,data:Qtn5eoT8o2f/yK+R23j1WRFSORK+FztR7lpSWwygC7JBi1UT9dTx0/VMok+8yMUnVTuJYe70P6hTBcoXEmrBfe2Ybs65Bl5g4KbWNAG5iRCuWvMCHjFRqezjJ/aL09Oss/zEPz4FYT8vI8LGocZASc8L1AiyE0Ht8m48pnb4FyA=,iv:sebZ7lkY2rOJcO1UJthmujP/qxGoBaOwNlDXGXoUKbI=,tag:3qkUJI2L8iIEwmdLycIobQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0