apiVersion: v1
kind: Secret
metadata:
    name: nickatcher-vpn
    namespace: nickatcher
type: Opaque
stringData:
    vpn-service-provider: ENC[AES256_GCM,data:cHSNDhYf/bpX,iv:PXNvRKu54QY/l9thKlZemFoMUdFq8jLGaO3XoBebTLs=,tag:/pUVer19eWFocetA2bhG3g==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:mxjuXsXAfgUPFPryEWEFNbBwAlTOZsrJ6YcJ6D3fUXMp4euvOFpJXC8bU/g=,iv:px5qbymDDzHyPnEk65M9jWIQXyyJaFeohcpP0rwup9o=,tag:DRV5YM/iARSYk+TltBToyQ==,type:str]
    wireguard-private-key: ENC[AES256_GCM,data:2ScC/NQuTGkX0GQmpO5jCktSgzDE9DiUNWlmnaq69d1fgE39OwN9ueV1TVI=,iv:8Bb59i8ga5svze5M4fURKNwJhWYeKcNg5LFTtqQvwhg=,tag:PvZFU6/vwRR7VYAqVy74mw==,type:str]
    server-cities: ENC[AES256_GCM,data:fBShprYerps=,iv:qAWOemjSdHAx5pBjlm3TNOCiwg94xXT3lD9Z5JqnXy8=,tag:8b9bFum/THYZRx2bpLYjuA==,type:str]
sops:
    age:
        - recipient: age1n7m4qddze6jmky0zzgasxr2fsea25t4ejppzv0flftsuzhrytgaqm49c2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNVZJTzgya1UvdEtuSEZq
            bnFKL0xPdXAwNmdqVW1CWVp6V3ZRcG5McWpRClEyWm80Nm9pcUJMRk41T1FLK3NK
            dXR4M0R3SExZc2RxZW41L05VNmRJVjgKLS0tIEtVMmxIZGpSOHNtNnN1cnBvd0l5
            azNGUjBTaWhPRkhleUxWNmkrWkFTN0kK2jwAFIkGfVv77xQAg/CXk8c1VMh9FoOy
            GMcZTAxnYoPSpOHOmtUA6B7ARRXCcbppbj152crukOa12RXBRs08rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T16:34:36Z"
    mac: ENC[AES256_GCM,data:3U242M98vgAF7mlHQ2iPKdRH4kDZlKgun2oAKnTWZO22zXyGjQqJ7R74a+tZ1E5rlkI/YJlVP2BKOSOgqmfYtYsvBQ6djz7+oKj8QJ+8ezni09SaHXjx01IbjT52Ht25JOMlkmt81kkvSl3b5uinMQMzr5+d66MfoohIsjY3SCw=,iv:DUemLhUmOpoy8sUgCLWWSkNqd2nDOqBYKf9JvxOiB9Y=,tag:D9dGu17BvexAjDPEFAZOHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
