apiVersion: v1
kind: Secret
metadata:
    name: matrix-call-jwt-env
    namespace: matrix-call
type: Opaque
stringData:
    LIVEKIT_SECRET: ENC[AES256_GCM,data:NelpR/qU8/oIPkveHdazeoM3FS8kK5cTO8iaN9HZlYw=,iv:tLPM5I9Pveh9AflucDw2fRSpPKhccLw7i30SFCnFOtE=,tag:5i+I005Sp2s/ePwAcSCnJA==,type:str]
sops:
    age:
        - recipient: age1n7m4qddze6jmky0zzgasxr2fsea25t4ejppzv0flftsuzhrytgaqm49c2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQlNJdWhERTBodnpkbzg0
            eDFSdER0Y2Y5ajRzZ2RoK3grL3FrbG1RMFdNCmU2bENHNCtsSDQzYXhVRHFSekMy
            UlJuTldTaVFGUEkwYUp0ZXpXMXAwdzAKLS0tIHE4OFVON202eVlJNmhaZWVQOFVl
            RVh6YmJ3TnR0RlVCTTlFd01mRWRPdjQKheCXO79aKsFm5yHc9KtqaxQFxNAgaVh2
            lCQ4SM6rv0t5uqxgaBCDse5D84i8t7DaZI854MJHoyle1npM2mC08g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T03:16:47Z"
    mac: ENC[AES256_GCM,data:feoPN5siyfNrN/pga0+xSIBMJ9r4cImwSqstcHHjL/gxTnGM+/64Fmw3yLfE5vsl0QwmOSdmFx4Kzt8gu6rSGONycd+JVyL5QonmFebEc4FxcJedKxWizFZmEF3aBwiQjAYimQl0/nqfVn8zozBX/jXmYC4Wfsi2MX/uOoIK6NQ=,iv:DKgXsMYruzUkkFyJJtFT8/CCFOaehTzSbf9Du2/mTIM=,tag:kUdSTiqzV+VNTnOI24EcqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0