apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: unifi-transport
  namespace: unifi
spec:
  insecureSkipVerify: true
  serverName: unifi-controller
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: unifi-allow-backend
  namespace: unifi
spec:
  podSelector:
    matchLabels:
      app: unifi-controller
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: flux-system
