apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo
  namespace: sftpgo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: sftpgo
        image: drakkan/sftpgo:v2.7.0
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: SFTPGO_DATA_PROVIDER__DRIVER
          value: sqlite
        - name: SFTPGO_DATA_PROVIDER__NAME
          value: /srv/sftpgo/sftpgo.db
        - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
          value: "true"
        - name: SFTPGO_DEFAULT_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: sftpgo-secrets
              key: default-admin-username
        - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sftpgo-secrets
              key: default-admin-password
        - name: SFTPGO_SFTPD__BINDINGS__0__PORT
          value: "2022"
        - name: SFTPGO_HTTPD__BINDINGS__0__PORT
          value: "8080"
        - name: SFTPGO_TELEMETRY__BIND_PORT
          value: "10000"
        - name: SFTPGO_TELEMETRY__BIND_ADDRESS
          value: "0.0.0.0"
        ports:
        - containerPort: 2022
          hostPort: 2022
          name: sftp
        - containerPort: 8080
          name: http
        - containerPort: 10000
          name: telemetry
        volumeMounts:
        - name: data
          mountPath: /srv/sftpgo
        - name: home
          mountPath: /var/lib/sftpgo
        livenessProbe:
          httpGet:
            path: /healthz
            port: telemetry
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: telemetry
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: data
        hostPath:
          path: /storage/appdata/sftpgo/data
          type: DirectoryOrCreate
      - name: home
        hostPath:
          path: /storage/appdata/sftpgo/home
          type: DirectoryOrCreate
