apiVersion: v1
kind: Secret
metadata:
    name: sftpgo-secrets
    namespace: sftpgo
type: Opaque
stringData:
    default-admin-username: ENC[AES256_GCM,data:AsW3169yeGA=,iv:tbMxFEhpRKLoR4PjAe8LpkyF8+Qx7MR6ZFSYacoEKto=,tag:ioy37OaTk2kOkMj2k4opIw==,type:str]
    default-admin-password: ENC[AES256_GCM,data:N1Y9+7nOD+5zzuY=,iv:BVqNX/tddQ5+XdlHqIjpLjtvBKTRLrIb739Ypswon20=,tag:ivMyZ8iP9yd2EZyzo50BvQ==,type:str]
sops:
    age:
        - recipient: age1n7m4qddze6jmky0zzgasxr2fsea25t4ejppzv0flftsuzhrytgaqm49c2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR1dzWncvMW5MV29tV2FB
            Y244cXJHMjB0aDM5UzZXaFBGSzdvdmltaERrCjFMTm1UMGJuWnZvenRxZzFYVjJU
            SzFaYm5GS1doN0h5SVJuVDFkYXBhNWcKLS0tIEFxakhmdWpBa0xzZUNsM2t6THFI
            eUdiamloMEJhSjFTR1pDR0ZjanpSTk0Kywf8qYhCQ34fcCUmb0crD4HDJKT+Jhot
            s4159Zn4vYsHb3/aGzlBbE7INtRXxxCWUbHt/1BAKqJJqyC3zGwQYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:53:56Z"
    mac: ENC[AES256_GCM,data:ilxkNkil+Vy2JF7bEQT2PjzgUYp9MuJdaYGau0ck6iFoz+1qpcGkAKCYV5uiXUIKfYbfAW6xDByhHLLD39v/7/XAvhfvOR+FUp2GJC+ywM6GX+napcIiGAQb9Dzsg1j3DgjKBGXkZ7/a5j8UvkwgZBwv5fI3BESbMyKSks/c8Rk=,iv:Fg+GP5n4RfNrqhywkvXjshYMaibcL+elmLhWhOy7kJ4=,tag:iQYtoXKf2009+ldrToqPqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
